name: Run main.py on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run main.py
      run: |
        python source/BUG/mathematics.py
        python source/BUG/strings.py
        python source/BUG/logic.py
        python source/BUG/structures.py
        python source/BUG/forExperts.py
